# Generated by Django 5.0.2 on 2024-03-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cemail', models.EmailField(max_length=254)),
                ('cmobile', models.BigIntegerField(max_length=50)),
                ('cage', models.IntegerField(max_length=50)),
                ('cgender', models.CharField(max_length=50)),
            ],
        ),
    ]
