# Generated by Django 5.0.2 on 2024-03-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_rename_contact_contact1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact1',
            name='caddress',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
